"""trigram index for entity aliases

Revision ID: 1e043a5decc8
Revises: 7cfda843c2e9
Create Date: 2026-06-22 23:43:17.082740
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '1e043a5decc8'
down_revision: Union[str, None] = '7cfda843c2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('entity_aliases_alias_idx'), table_name='entity_aliases')
    op.create_index('entity_aliases_alias_trgm_idx', 'entity_aliases', ['alias'], unique=False, postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})
    op.create_index('entity_aliases_canonical_idx', 'entity_aliases', ['entity_type', 'canonical_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('entity_aliases_canonical_idx', table_name='entity_aliases')
    op.drop_index('entity_aliases_alias_trgm_idx', table_name='entity_aliases', postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})
    op.create_index(op.f('entity_aliases_alias_idx'), 'entity_aliases', ['alias'], unique=False)
    # ### end Alembic commands ###
