"""answer_cache share_id

Revision ID: 1e337a14d9ce
Revises: 1e043a5decc8
Create Date: 2026-06-22 23:54:04.918257
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '1e337a14d9ce'
down_revision: Union[str, None] = '1e043a5decc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_cache', sa.Column('share_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'answer_cache', ['share_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer_cache', type_='unique')
    op.drop_column('answer_cache', 'share_id')
    # ### end Alembic commands ###
