"""initial schema

Revision ID: 7cfda843c2e9
Revises: 
Create Date: 2026-06-22 23:30:56.358468
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '7cfda843c2e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=True),
    sa.Column('answer_json', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_question')
    )
    op.create_index('answer_cache_embedding_idx', 'answer_cache', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('canonical_id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('entity_aliases_alias_idx', 'entity_aliases', ['alias'], unique=False)
    op.create_index('entity_aliases_embedding_idx', 'entity_aliases', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('players',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_inches', sa.SmallInteger(), nullable=True),
    sa.Column('weight_lbs', sa.SmallInteger(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('rookie_season', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index('players_full_name_idx', 'players', ['full_name'], unique=False)
    op.create_table('query_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_index('query_examples_embedding_idx', 'query_examples', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('seasons',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('season')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('games',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.SmallInteger(), nullable=False),
    sa.Column('season_type', sa.String(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('stadium', sa.String(), nullable=True),
    sa.Column('roof', sa.String(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['season'], ['seasons.season'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index('games_away_team_idx', 'games', ['away_team'], unique=False)
    op.create_index('games_home_team_idx', 'games', ['home_team'], unique=False)
    op.create_index('games_season_week_idx', 'games', ['season', 'week'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('games_played', sa.SmallInteger(), nullable=True),
    sa.Column('passing_yards', sa.Integer(), nullable=True),
    sa.Column('passing_tds', sa.SmallInteger(), nullable=True),
    sa.Column('interceptions', sa.SmallInteger(), nullable=True),
    sa.Column('rushing_yards', sa.Integer(), nullable=True),
    sa.Column('rushing_tds', sa.SmallInteger(), nullable=True),
    sa.Column('receptions', sa.SmallInteger(), nullable=True),
    sa.Column('receiving_yards', sa.Integer(), nullable=True),
    sa.Column('receiving_tds', sa.SmallInteger(), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season'], ['seasons.season'], ),
    sa.PrimaryKeyConstraint('player_id', 'season', 'season_type')
    )
    op.create_index('pss_season_idx', 'player_season_stats', ['season'], unique=False)
    op.create_table('player_game_stats',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('completions', sa.SmallInteger(), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), nullable=True),
    sa.Column('passing_yards', sa.Integer(), nullable=True),
    sa.Column('passing_tds', sa.SmallInteger(), nullable=True),
    sa.Column('interceptions', sa.SmallInteger(), nullable=True),
    sa.Column('sacks', sa.Float(), nullable=True),
    sa.Column('carries', sa.SmallInteger(), nullable=True),
    sa.Column('rushing_yards', sa.Integer(), nullable=True),
    sa.Column('rushing_tds', sa.SmallInteger(), nullable=True),
    sa.Column('targets', sa.SmallInteger(), nullable=True),
    sa.Column('receptions', sa.SmallInteger(), nullable=True),
    sa.Column('receiving_yards', sa.Integer(), nullable=True),
    sa.Column('receiving_tds', sa.SmallInteger(), nullable=True),
    sa.Column('fumbles', sa.SmallInteger(), nullable=True),
    sa.Column('fumbles_lost', sa.SmallInteger(), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_index('pgs_game_idx', 'player_game_stats', ['game_id'], unique=False)
    op.create_index('pgs_team_idx', 'player_game_stats', ['team_id'], unique=False)
    op.create_table('plays',
    sa.Column('play_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('posteam', sa.String(), nullable=True),
    sa.Column('defteam', sa.String(), nullable=True),
    sa.Column('qtr', sa.SmallInteger(), nullable=True),
    sa.Column('down', sa.SmallInteger(), nullable=True),
    sa.Column('yards_to_go', sa.SmallInteger(), nullable=True),
    sa.Column('yardline_100', sa.SmallInteger(), nullable=True),
    sa.Column('play_type', sa.String(), nullable=True),
    sa.Column('yards_gained', sa.SmallInteger(), nullable=True),
    sa.Column('epa', sa.Float(), nullable=True),
    sa.Column('wp', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('passer_player_id', sa.String(), nullable=True),
    sa.Column('rusher_player_id', sa.String(), nullable=True),
    sa.Column('receiver_player_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['defteam'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['posteam'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('play_id')
    )
    op.create_index('plays_game_idx', 'plays', ['game_id'], unique=False)
    op.create_index('plays_situational_idx', 'plays', ['down', 'qtr', 'play_type'], unique=False)
    op.create_table('team_game_stats',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('points_for', sa.SmallInteger(), nullable=True),
    sa.Column('points_against', sa.SmallInteger(), nullable=True),
    sa.Column('total_yards', sa.Integer(), nullable=True),
    sa.Column('passing_yards', sa.Integer(), nullable=True),
    sa.Column('rushing_yards', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.SmallInteger(), nullable=True),
    sa.Column('time_of_possession_sec', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_id', 'game_id')
    )
    op.create_index('tgs_game_idx', 'team_game_stats', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tgs_game_idx', table_name='team_game_stats')
    op.drop_table('team_game_stats')
    op.drop_index('plays_situational_idx', table_name='plays')
    op.drop_index('plays_game_idx', table_name='plays')
    op.drop_table('plays')
    op.drop_index('pgs_team_idx', table_name='player_game_stats')
    op.drop_index('pgs_game_idx', table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_index('pss_season_idx', table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_index('games_season_week_idx', table_name='games')
    op.drop_index('games_home_team_idx', table_name='games')
    op.drop_index('games_away_team_idx', table_name='games')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_index('query_examples_embedding_idx', table_name='query_examples', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('query_examples')
    op.drop_index('players_full_name_idx', table_name='players')
    op.drop_table('players')
    op.drop_index('entity_aliases_embedding_idx', table_name='entity_aliases', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('entity_aliases_alias_idx', table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index('answer_cache_embedding_idx', table_name='answer_cache', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('answer_cache')
    # ### end Alembic commands ###
