"""defensive stats columns

Revision ID: 20cdfefbc4a5
Revises: 1e337a14d9ce
Create Date: 2026-06-23 23:34:24.112102
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '20cdfefbc4a5'
down_revision: Union[str, None] = '1e337a14d9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_game_stats', sa.Column('tackles', sa.SmallInteger(), nullable=True))
    op.add_column('player_game_stats', sa.Column('def_sacks', sa.Float(), nullable=True))
    op.add_column('player_game_stats', sa.Column('def_interceptions', sa.SmallInteger(), nullable=True))
    op.add_column('player_season_stats', sa.Column('tackles', sa.SmallInteger(), nullable=True))
    op.add_column('player_season_stats', sa.Column('def_sacks', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('def_interceptions', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_season_stats', 'def_interceptions')
    op.drop_column('player_season_stats', 'def_sacks')
    op.drop_column('player_season_stats', 'tackles')
    op.drop_column('player_game_stats', 'def_interceptions')
    op.drop_column('player_game_stats', 'def_sacks')
    op.drop_column('player_game_stats', 'tackles')
    # ### end Alembic commands ###
