#!/usr/bin/env python3
"""Generate apps/api/app/espn_ids.py — GSIS player id -> ESPN player id.

Pulls every NFL team roster from ESPN's public site API and name-matches the
players seeded in the demo warehouse. Run from the repo root anywhere with
open network access (a laptop, CI, the deploy build):

    python scripts/fetch_espn_ids.py

Idempotent: rewrites the generated module in full each run. Names are matched
case-insensitively with punctuation/suffix normalization; anything unmatched
is reported so it can be resolved by hand (the frontend falls back to an
initials avatar for players without an id).
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "apps" / "api"))

from app.seed import SEED_PLAYERS  # noqa: E402

TEAMS_URL = "https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams"
ROSTER_URL = (
    "https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/{team_id}/roster"
)
OUT = REPO / "apps" / "api" / "app" / "espn_ids.py"

_SUFFIXES = {"jr", "sr", "ii", "iii", "iv", "v"}


def _norm(name: str) -> str:
    """'Michael Pittman Jr.' -> 'michael pittman'; 'D.J. Moore' -> 'dj moore'."""
    words = re.sub(r"[.'’]", "", name.lower()).split()
    return " ".join(w for w in words if w not in _SUFFIXES)


def _get(url: str) -> dict:
    with urllib.request.urlopen(url, timeout=30) as resp:
        return json.load(resp)


def main() -> int:
    teams = _get(TEAMS_URL)["sports"][0]["leagues"][0]["teams"]
    espn_by_name: dict[str, int] = {}
    for entry in teams:
        roster = _get(ROSTER_URL.format(team_id=entry["team"]["id"]))
        for group in roster.get("athletes", []):
            for athlete in group.get("items", []):
                espn_by_name.setdefault(_norm(athlete["fullName"]), int(athlete["id"]))

    mapping: dict[str, int] = {}
    missing: list[str] = []
    for player_id, full_name, _pos, _team in SEED_PLAYERS:
        espn_id = espn_by_name.get(_norm(full_name))
        if espn_id is None:
            missing.append(full_name)
        else:
            mapping[player_id] = espn_id

    lines = [
        '"""GENERATED by scripts/fetch_espn_ids.py — do not edit by hand."""',
        "",
        "ESPN_IDS: dict[str, int] = {",
    ]
    for player_id, full_name, _pos, _team in SEED_PLAYERS:
        if player_id in mapping:
            lines.append(f'    "{player_id}": {mapping[player_id]},  # {full_name}')
    lines += ["}", ""]
    OUT.write_text("\n".join(lines))

    print(f"matched {len(mapping)}/{len(SEED_PLAYERS)} players -> {OUT}")
    if missing:
        print("unmatched (initials avatar will be used):")
        for name in missing:
            print(f"  - {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
