"""GENERATED by scripts/fetch_espn_ids.py — do not edit by hand.

Run the script anywhere with open network access to populate this mapping;
players without an entry get an initials avatar in the UI.
"""

ESPN_IDS: dict[str, int] = {}
